---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

params:
  ATTENDEE_SERVICE_URL:

inputs:
- name: attendee-service-source

run:
  path: attendee-service-source/ci/tasks/test.sh

